### ISSUE TITLE
Proper Attribution

### ISSUE THREAD

**Issue by RedYetiDev** [AcaiBerii/Blooket.JS-reborn#2]
Hello, 
I am glad to see you're taking an interest in my project, `Blooket.JS`. I want you to be aware that you **may** be breaking my license. Let me explain:

According to my license, you are required to give me attribution for this project. My username is also not anywhere on your repo. So, I think you might be breaking my license.

In order to fix this issue, all you would need to is add a little note letting anyone know that I created this project. An example: "Blooket.JS was originally created by [RedYetiDev](https://github.com/redyetidev) and the original project can be found [here](https://github.com/redyetidev/blooket.js)"

Thank you for understanding,
[RedYetiDev](https://github.com/redyetidev)

**EDIT: Made message sound better**

**Comment by AcaiBerii** [comment]
Woops, sorry. Forgot to read the license.

I am very stupid btwwww and i have school as well

**Comment by RedYetiDev** [comment]
No problem, thank you for fixing your README file.
